[project]
name = "ernest-math"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter-book>=1.0.4.post1",
    "matplotlib>=3.10.6",
    "notebook>=7.4.7",
    "plotly>=6.3.1",
    "sympy>=1.14.0",
]
